# Generated by Django 3.0.3 on 2020-02-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Reader',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
