# Generated by Django 3.0.3 on 2020-02-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200212_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
