# Generated by Django 3.0.3 on 2020-02-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200216_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(default='default reader', on_delete=django.db.models.deletion.CASCADE, related_name='Books_Reader', to='p_library.Reader'),
        ),
    ]
